# Generated by Django 5.1.5 on 2025-05-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0029_remove_businesspartner_partner_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspartner',
            old_name='full_name',
            new_name='name',
        ),
    ]
