# Generated by Django 5.1.5 on 2025-05-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0030_rename_full_name_businesspartner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='passbook',
            field=models.ImageField(default='', upload_to='attachments/'),
            preserve_default=False,
        ),
    ]
